
public class MovieTest {

	public static void main(String[] args) throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		Movie m1 = new Movie(111, "Devara", "Shiva");
		Movie m2 = new Movie(222, "RRR", "SS Rajamouli");
		Movie m3 = new Movie(111, "Devara", "Shiva");
		
		//Shallow cloning
		Movie m4 = m1;
		
		//Deep cloning (Creating Independent Object)
		Movie m5 = (Movie) m2.clone();
		
		System.out.println(m1.toString()); //It is the implementation of toString() method, it is automatically called when an reference variables is printed 
		System.out.println(m2);
		
		System.out.println(m1.hashCode());//to find the address of object hashCode() should be generated
		System.out.println(m2.hashCode());// It is a unique ID which will be generated by JVM based on the address of memory
		System.out.println(m3.hashCode());
		
		// == operator always meant for reference comparison only
		System.out.println(m1 == m2);
		System.out.println(m1 == m3);
		System.out.println(m4 == m1);
		
		//Object class .equals() is meant for reference comparison only
		System.out.println(m1.equals(m2));
		System.out.println(m1.equals(m3));
		System.out.println(m4.equals(m1));
		
		//String class .equals() method is meant for content comparison
		String s1 = new String("Java");
		String s2 = new String("Java");
		System.out.println(s1.equals(s2));
	}
	

}
